export const TYPES = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_PRODUCT_SUCCEDD: "GET_PRODUCT_SUCCEDD",
  GET_PRODUCT_LOGOUT: "GET_PRODUCT_LOGOUT",
  GET_TOKEN_SUCCEDD: "GET_TOKEN_SUCCEDD",
  LOGOUT_SUCCEDD: "LOGOUT_SUCCEDD",
};
