export const TYPES = {
  GET_LOCATION_SUCCEED: "GET_LOCATION_SUCCEED",
  GET_LON_SUCCEED: "GET_LON_SUCCEED",
  GET_SEARCH_SUCCEED: "GET_SEARCH_SUCCEED",
  GET_WEATHER_SUCCEED: "GET_WEATHER_SUCCEED",
  GET_FORECAST_SUCCEED: "GET_FORECAST_SUCCEED",
};
